### ISSUE TITLE
Add a contract to coroutineScope, withContext and operator fun invoke for CoroutineDispatcher

### ISSUE THREAD

**Issue by LouisCAD** [Kotlin/kotlinx.coroutines#1257]
Now that there is an EAP kotlinx.coroutines version for 1.3.40 EAP, and since 1.3.40 supports contracts for suspending functions, we can add contracts for the lambdas of the following functions in this library:
- `coroutineScope`
- `withContext`
- `invoke` (extension function for `CoroutineDispatcher`)

I can make a PR on the 1.3.40-eap branch.

**Comment by qwwdfsad** [comment]
Please hold on with PR unless the `develop` branch is fully migrated to Kotlin 1.3.40

**Comment by qwwdfsad** [comment]
1.3.40 is in `develop`.
Feel free to create a PR (or let me know if you don't have time to or just don't want to)

**Comment by dkhalanskyjb** [comment]
Looks like this was fixed in https://github.com/Kotlin/kotlinx.coroutines/pull/2030.

**Comment by LouisCAD** [comment]
@dkhalanskyjb Wasn't it reverted in this commit? https://github.com/Kotlin/kotlinx.coroutines/commit/1253cb9adaed18cba1566deb171fce2e554476a2

**Comment by dkhalanskyjb** [comment]
GitHub tells me:
> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

Also, `git blame` shows #2030 as the PR which introduced the change (which is currently there, in the codebase).

**Comment by LouisCAD** [comment]
Alright.

The `operator fun invoke` extension for `CoroutineDispatcher` still doesn't have the contract though:
https://github.com/Kotlin/kotlinx.coroutines/blob/7cc59e4f2b15961f10e94cddd3f2fb7fe331328a/kotlinx-coroutines-core/common/src/Builders.common.kt#L175-L184

**Comment by LouisCAD** [comment]
The reason is architectural, relative to the compiler front-end, I found my own issue, reported 2 years ago 😅

https://youtrack.jetbrains.com/issue/KT-32313
